### ISSUE TITLE
installation instructions : Failed building wheel 

### ISSUE THREAD

**Issue by chayan18** [befelix/safe_learning#5]
Hi, with reference to your earlier comments (https://github.com/befelix/safe_learning/commit/9fc747515aa073bea86656b8faea751475b4c3ae) I have made the  necessary changes , but still I am getting these errors ,

Failed building wheel for cvxpy

Failed building wheel for subprocess32

Failed building wheel for fastcache

 error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

How to resolve, thanks

**Comment by befelix** [comment]
This seems to be a problem with installing `cvxpy`, a dependency. In particular it looks like you don't have the compiler `gcc` installed (a non-python dependency). The solution depends on your operating system, but on linux/ubuntu you need to install `build-essentials`.

**Comment by chayan18** [comment]
Hi, "--process-dependency-links" is not working for me so I am installing the packages by pip command and  I figure out that the problem is in installing cvxpy by  pip command. I did some google search and peoples are suggesting  to install via conda rather pip. Also conda and pip often conflict. So I am thinking to reinstall  each package by using conda . What is your opinion regarding this matter and please let me know the necessary changes  in the command.

Thanks

**Comment by befelix** [comment]
Could you post the terminal output when you follow the installation instructions on the readme?

Also what platform are you on? The installation is tested in the docker containers on Linux. I have no experience installing the library and its dependencies on windows or mac.

**Comment by chayan18** [comment]
Hi, I am using Ubuntu 16.04.5. 

I have attached both the screenshot and the pdf version of the output of the command ,
``pip install . --process-dependency-links``

In the pdf file please see  pages 1,13 and 14 , I have highlighted the error commands in pages 13,14.


Thanks.


[terminal-display.pdf](https://github.com/befelix/safe_learning/files/2931274/terminal-display.pdf)
![terminal-display](https://user-images.githubusercontent.com/39224486/53811308-1491b280-3f7f-11e9-9e0d-6da9160e03f5.png)

**Comment by befelix** [comment]
Can you make sure that `python-dev` respectively `python3-dev` is
installed? It looks like it's complaining about missing header files for
compilation.

**Comment by chayan18** [comment]
Hi, thanks for your helpful suggestions. It works. I have installed all the necessary packages. However while running the example code " inverted_pendulum.ipynb" , this error is coming,

AttributeError: 'module' object has no attribute 'to_rgba'

I have attached the pdf version of this web page, please see pages 6, 8,9,10,11

Thanks

[inv_pend.pdf](https://github.com/befelix/safe_learning/files/2936194/inv_pend.pdf)

**Comment by chayan18** [comment]
Hi, thanks for your helpful suggestions. It works. I have installed all the necessary packages. However while running the example code " inverted_pendulum.ipynb" , this error was coming,

AttributeError: 'module' object has no attribute 'to_rgba'

I google search the issues and update matplotlib according to the suggestion. 
At this I am getting new errors
---------------------------------------------------------------------------
FailedPreconditionError                   Traceback (most recent call last)
<ipython-input-27-72245a7797cb> in <module>()
      6     #session.run(adapt_policy_mean, feed_dict=rl.feed_dict)
      7     sess = tf.Session()
----> 8     sess.run(adapt_policy_mean, feed_dict=rl.feed_dict)

/home/ayan/slearn/venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    903     try:
    904       result = self._run(None, fetches, feed_dict, options_ptr,
--> 905                          run_metadata_ptr)
    906       if run_metadata:
    907         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/home/ayan/slearn/venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1135     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1136       results = self._do_run(handle, final_targets, final_fetches,
-> 1137                              feed_dict_tensor, options, run_metadata)
   1138     else:
   1139       results = []

/home/ayan/slearn/venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1353     if handle is None:
   1354       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
-> 1355                            options, run_metadata)
   1356     else:
   1357       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

/home/ayan/slearn/venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1372         except KeyError:
   1373           pass
-> 1374       raise type(e)(node_def, op, message)
   1375 
   1376   def _extend_graph(self):

FailedPreconditionError: Attempting to use uninitialized value triangulation_1/vertex_values
	 [[Node: triangulation_1/vertex_values/read = Identity[T=DT_DOUBLE, _class=["loc:@triangulation_1/vertex_values"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](triangulation_1/vertex_values)]]

Caused by op u'triangulation_1/vertex_values/read', defined at:
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ayan/slearn/venv/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 499, in start
    self.io_loop.start()
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/tornado/ioloop.py", line 1073, in start
    handler_func(fd_obj, events)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2714, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2818, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-6dd0803ee454>", line 10, in <module>
    project=True)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/safe_learning/functions.py", line 1411, in __init__
    name='vertex_values')
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 233, in __init__
    constraint=constraint)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 381, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 131, in identity
    return gen_array_ops.identity(input, name=name)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2051, in identity
    "Identity", input=input, name=name)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/home/ayan/slearn/venv/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value triangulation_1/vertex_values
	 [[Node: triangulation_1/vertex_values/read = Identity[T=DT_DOUBLE, _class=["loc:@triangulation_1/vertex_values"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](triangulation_1/vertex_values)]]







Also I have attached  the pdf version of this web page, please see pages 5,6,8,9,10


Thanks


[inv_pend.pdf](https://github.com/befelix/safe_learning/files/2945762/inv_pend.pdf)

**Comment by befelix** [comment]
I just did a fresh install of the code and the notebook runs fine in its original form without any problems.
The reason it is not working for you is that you modified the notebook code. In particular in cell [15] you're defining a new session, rather than using the existing interactive session defined at the beginning of the code. I would guess that is the source of your problems. Please use the original code provided. I cannot provide support for modified code.
